net.sf.jasperreports.xml.load.handler.default=net.sf.jasperreports.engine.xml.JRXmlLoader
net.sf.jasperreports.compiler.java.executable=internal
net.sf.jasperreports.compiler.java.classpath=app.jar:lib/*
